---
- name: Unpack tomcat tarball file
  unarchive:
    src: apache-tomcat-{{tomcat_version}}.tar.gz
    dest: /opt/
    creates: /opt/apache-tomcat-{{tomcat_version}}
    owner: tomcat
    group: tomcat
    keep_newer: yes

- name: Create link pointing to the current installation
  file:
    src: /opt/apache-tomcat-{{tomcat_version}}
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    state: link
